version: 0.2

phases:
  pre_build:
    commands:
      # 1. 리전을 '도쿄'로 고정합니다.
      - ECR_REGION=ap-northeast-1
      - echo "Logging in to Amazon ECR (Tokyo)..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
      # 2. 리포지토리 URI (도쿄 ECR의 리포 이름과 일치해야 함)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/deploy-land/app2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # 3. (순서 수정) 'npm install'을 먼저 실행
      - echo "Installing dependencies..."
      - npm install
      
      # 4. (package.json 수정 필요) 'npm test' 실행
      - echo "Running tests..."
      - npm test
      
      # 5. Docker 이미지 빌드
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # 6. ECR로 푸시
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Push successful."
      
      # 7. (가장 중요!) CodePipeline의 'Deploy' 단계를 위한 파일 생성
      #    App Runner 서비스 이름(sample-app-service)이 일치해야 합니다.
      - echo "Writing image definitions file..."
      - printf '[{"name":"sample-app-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

# 8. (가장 중요!) 'Deploy' 단계로 imagedefinitions.json 파일을 전달
artifacts:
  files:
    - imagedefinitions.json
