version: 0.2

phases:
  pre_build:
    commands:
      # 1. 서울 ECR 로그인 (ap-northeast-2)
      - ECR_REGION=ap-northeast-2
      - echo "Logging in to Amazon ECR (Seoul)..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 761111057533.dkr.ecr.$ECR_REGION.amazonaws.com      
      # 2. ECR 리포지토리 URI (2단계에서 만든 ECR 리포 이름과 일치)
      - REPOSITORY_URI=761111057533.dkr.ecr.$ECR_REGION.amazonaws.com/deploy-land/app2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # 3. 'npm install' 및 'npm test' 실행
      - echo "Installing dependencies and running tests..."
      - npm install
      - npm test # (package.json에서 "exit 0"으로 수정했는지 확인!)
      
      # 4. Docker 이미지 빌드
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # 5. ECR로 푸시
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # 6. (⭐️ EB용 핵심 ⭐️)
      # CodePipeline의 'Deploy' 단계로 전달할 "Dockerrun.aws.json" 파일 생성
      - echo "Creating Dockerrun.aws.json for Elastic Beanstalk..."
      - |
        cat > Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "$REPOSITORY_URI:$IMAGE_TAG",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 8080
            }
          ]
        }
        EOF

# 7. (⭐️ EB용 핵심 ⭐️)
# "Deploy" 단계는 소스 코드가 아니라, 오직 "Dockerrun.aws.json" 파일 1개만 필요로 함
artifacts:
  files:
    - Dockerrun.aws.json
