version: 0.2

phases:
  pre_build:
    commands:
      - ECR_REGION=ap-northeast-1
      - echo "Logging in to Amazon ECR (Tokyo)..."
      # 1. $AWS_ACCOUNT_ID 대신 실제 계정 ID (761111057533)를 하드코딩합니다.
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 761111057533.dkr.ecr.$ECR_REGION.amazonaws.com
      
      # 2. REPOSITORY_URI에도 실제 계정 ID (761111057533)를 하드코딩합니다.
      - REPOSITORY_URI=761111057533.dkr.ecr.$ECR_REGION.amazonaws.com/deploy-land/app2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Installing dependencies..."
      - npm install

      - echo "Running tests..."
      - npm test

      - echo "Building the Docker image..."
      - docker build -t deploy-land/app2:latest .
      - docker tag deploy-land/app2:latest $REPOSITORY_URI:latest
      - docker tag deploy-land/app2:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Push successful."

      - echo "Starting AWS App Runner deployment..."
      - aws apprunner start-deployment --service-arn $APPRUNNER_SERVICE_ARN --region $ECR_REGION
      - echo "App Runner deployment triggered successfully!"
