version: 0.2

phases:
  pre_build:
    commands:
      # 이 라인을 삭제하세요 ⭐
      # - echo $DOCKER_HUB_PASS | docker login --username $DOCKER_HUB_USER --password-stdin
      
      # ECR 로그인만 남겨두세요
      - ECR_REGION=ap-northeast-1
      - echo "Logging in to Amazon ECR (Tokyo)..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
      
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/deploy-land/app2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # 3. 'npm install'을 먼저 실행
      - echo "Installing dependencies..."
      - npm install

      # 4. 'npm test' 실행 (package.json 수정으로 통과됨)
      - echo "Running tests..."
      - npm test

      # 5. Docker 이미지 빌드
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # 6. ECR로 푸시
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Push successful."

      - echo "Starting AWS App Runner deployment..."
      - aws apprunner start-deployment --service-arn arn:aws:apprunner:ap-northeast-1:761111057533:service/sample-app-service/a1b2c3d4e5f6 --region ap-northeast-1
